import Link from 'next/link';
import "./globals.css";
import { ToastContainer } from 'react-toastify';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav className="bg-white shadow-sm py-4">
          <div className="container mx-auto px-4 flex justify-between items-center">
            <Link href="/" className="text-xl font-bold text-blue-600">
              QuickShare
            </Link>
            <div className="space-x-4">
              <Link href="/" className="hover:text-blue-600">
                Upload
              </Link>
              <Link href="/text-posts" className="hover:text-blue-600">
                Text Posts
              </Link>
              <Link href="/files" className="hover:text-blue-600">
                Files
              </Link>
            </div>
          </div>
        </nav>
        <main>{children}</main>
        <ToastContainer position="bottom-right" autoClose={3000} />
      </body>
    </html>
  );
}
